apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: research-XSS-extra_js
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: guest




